---
- hosts: all
  become: yes

  tasks:
    - name: Set hostname
      lineinfile:
        path: /etc/hosts
        line: |
          {{ app_private_ip }} httpbin-app
          {{ tester_private_ip }} httpbin-tester
        state: present

    - name: Prepare app dir
      file:
        path: /app
        state: directory

    - name: Install packages
      package:
        name: '{{ item }}'
        state: present
      with_items:
        - htop
        - iftop
        - tmux
        - git
        - build-essential
        - libssl-dev
        - zlib1g-dev

    - name: Install wrk2
      shell: |
        git clone https://github.com/giltene/wrk2.git
        cd wrk2
        make
        cp wrk /usr/local/bin
      args:
        chdir: /app
